# ./.tmuxinator.yml

name: all-dev-servers-in-tmux
root: ./../../
set-remain-on-exit: on

windows:
  - editor:
      layout: tiled
      panes:
        # Multiline commands under pane are taken from: https://github.com/tmuxinator/tmuxinator#passing-directly-to-send-keys
        - docs:
            - yarn docs-in-dev-mode
        - Client:
            - cd webclient
            - npm run start-dev
        - JsonServer:
            - cd utils/db
            - ./start-json-server-for-mock-db.sh
        - redisServer:
            - cd servers/redis-for-socket-io
            - ./start-redis-server.sh
        - redisUI:
            - cd servers/redis-for-socket-io
            - ./start-redis-web-interface.sh
        - msgPipeline:
            - cd servers/msg-pipeline
            - ./start-redis-client-and-socket-server.sh
        - remServer:
            - cd servers/lumen-for-api
            - php -S localhost:8000 -t .
        - Terminal:
